#!/bin/bash

## setup mpi environment
source /usr/usc/openmpi/default/setup.sh

## prepend anaconda's bin, including python2.7
export PATH=/home/scec-00/mei/anaconda2/bin:$PATH

## prepend velocity model's lib
export TEST_UCVMC_TARGET=/home/scec-00/mei/TARGET_UCVMC
export UCVM_SRC_PATH=$TEST_UCVMC_TARGET/UCVMC
export UCVM_INSTALL_PATH=$TEST_UCVMC_TARGET/install

if [ $LD_LIBRARY_PATH ] ; then
  export LD_LIBRARY_PATH=$UCVM_INSTALL_PATH/lib/euclid3/lib:$UCVM_INSTALL_PATH/lib/proj-4/lib:$UCVM_INSTALL_PATH/model/cvms426/lib:$UCVM_INSTALL_PATH/model/cencal/lib:$LD_LIBRARY_PATH
  else
    export LD_LIBRARY_PATH=$UCVM_INSTALL_PATH/lib/euclid3/lib:$UCVM_INSTALL_PATH/lib/proj-4/lib:$UCVM_INSTALL_PATH/model/cvms426/lib:$UCVM_INSTALL_PATH/model/cencal/lib
fi
#echo $LD_LIBRARY_PATH

## setup python script
if [ $PYTHONPATH ] ; then 
  export PYTHONPATH=$PYTHONPATH:$UCVM_SRC_PATH/utilities/pycvm
  else
     export PYTHONPATH=$UCVM_SRC_PATH/utilities/pycvm
fi
#echo $PYTHONPATH



export TEST_TOP_PATH=/home/scec-00/mei/UCVM_REVIEW
export TEST_RESULT=${TEST_TOP_PATH}/RESULT/CrossSections

###############################################################################
# cross section call

cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.845,-123 -u 34.845,-115 -h 500 -v 50 -d vs -c cca -a d -s 0 -e 10000 -o cc_cca34_845.png 

cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.845,-123 -u 34.845,-115 -h 500 -v 50 -d vs -c cca -a b -g 2.5 -s 0 -e 10000 -o cc_cca34_845_b.png 

cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 35.345,-123 -u 35.345,-115 -h 500 -v 50 -d vs -c cca -a d -s 0 -e 10000 -o cc_cca34_345.png

cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 35.345,-123 -u 35.345,-115 -h 500 -v 50 -d vs -c cca -a b -g 2.5 -s 0 -e 10000 -o cc_cca34_345_b.png

cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.5,-123 -u 34.5,-115 -h 500 -v 50 -d vs -c cca -a b -g 2.5 -s 0 -e 10000 -o cc_cca34_5_b.png

cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.5,-123 -u 34.5,-115 -h 500 -v 50 -d vs -c cca -a d -s 0 -e 10000 -o cc_cca34_5.png

cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 35.135,-123 -u 35.135,-115 -h 500 -v 50 -d vs -c cca  -a b -g 2.5 -s 0 -e 10000 -o cc_cca35_135_b.png

cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 35.135,-123 -u 35.135,-115 -h 500 -v 50 -d vs -c cca -a d -s 0 -e 10000 -o cc_cca35_135.png

cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 35.245,-123 -u 35.245,-115 -h 500 -v 50 -d vs -c cca  -a b -g 2.5 -s 0 -e 10000 -o cc_cca35_245_b.png

cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 35.245,-123 -u 35.245,-115 -h 500 -v 50 -d vs -c cca  -a d -s 0 -e 10000 -o cc_cca35_245.png

cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.5,-118.60 -u 34.5,-118.70 -h 100 -v 10 -d vs -c cca  -a d -s 0 -e 10000 -o cc_cca34_5s.png

cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.5,-118.60 -u 34.5,-118.70 -h 100 -v 10 -d vs -c cca  -a b -g 2.5 -s 0 -e 10000 -o cc_cca34_5s_b.png






