#!/bin/bash

###############################################################################
# cross section call

#cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.5,-118.70 -u 34.5,-118.60 -h 100 -v 10 -d vs -c cca -a d -s 0 -e 5000 -o cross_118.7x_34.5_cca.png

#cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.5,-118.70 -u 34.5,-118.60 -h 100 -v 10 -d vs -c cvms -a d -s 0 -e 5000 -o cross_118.7x_34.5_cvms.png

#cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.5,-118.70 -u 34.5,-118.60 -h 100 -v 10 -d vs -c cvmsi -a d -s 0 -e 5000 -o cross_118.7x_34.5_cvmsi.png

#cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.5,-118.70 -u 34.5,-118.60 -h 100 -v 10 -d vs -c cvmh -a d -s 0 -e 5000 -o cross_118.7x_34.5_cvmh.png

#cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 35.21,-121 -u 35.21,-118.0 -h 100 -v 10 -d vs -c cca -a d -s 0 -e 5000 -o cross_121x_35.21_cca.png 

#cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 35.21,-121 -u 35.21,-118.0 -h 100 -v 10 -d vs -c cca -a b -s 0 -e 5000 -o cross_121x_35.21_cca_g.png -g 2.5

#cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 35.21,-119.39 -u 35.21,-119 -h 100 -v 10 -d vs -c cca -a d -s 0 -e 5000 -o cross_121x_35.21_cca.png 

#===========

cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.5,-118.70 -u 34.5,-118.60 -h 100 -v 10 -d vs -c cs173 -a d -s 0 -e 5000 -o cross_118.7x_34.5_cs173.png
cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.5,-118.70 -u 34.5,-118.60 -h 100 -v 10 -d vs -c cca -a d -s 0 -e 5000 -o cross_118.7x_34.5_cca.png



