#!/bin/bash

## setup mpi environment
source /usr/usc/openmpi/default/setup.sh

## prepend anaconda's bin, including python2.7
export PATH=/home/scec-00/mei/anaconda2/bin:$PATH


## prepend velocity model's lib
export TEST_UCVMC_TARGET=/home/scec-00/mei/TARGET_UCVMC
export UCVM_SRC_PATH=$TEST_UCVMC_TARGET/UCVMC
export UCVM_INSTALL_PATH=$TEST_UCVMC_TARGET/install

if [ $LD_LIBRARY_PATH ] ; then
  export LD_LIBRARY_PATH=$UCVM_INSTALL_PATH/lib/euclid3/lib:$UCVM_INSTALL_PATH/lib/proj-4/lib:$UCVM_INSTALL_PATH/model/cvms426/lib:$UCVM_INSTALL_PATH/model/cencal/lib:$LD_LIBRARY_PATH
  else
    export LD_LIBRARY_PATH=$UCVM_INSTALL_PATH/lib/euclid3/lib:$UCVM_INSTALL_PATH/lib/proj-4/lib:$UCVM_INSTALL_PATH/model/cvms426/lib:$UCVM_INSTALL_PATH/model/cencal/lib
fi
#echo $LD_LIBRARY_PATH

## setup python script
if [ $PYTHONPATH ] ; then 
  export PYTHONPATH=$PYTHONPATH:$UCVM_SRC_PATH/utilities/pycvm
  else
     export PYTHONPATH=$UCVM_SRC_PATH/utilities/pycvm
fi
#echo $PYTHONPATH




###############################################################################
# cross section call


#cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.5,-118.70 -u 34.5,-118.60 -h 100 -v 10 -d vs -c cca -a d -s 0 -e 5000 -o cross_118.7x_34.5_cca.png

#cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.5,-118.70 -u 34.5,-118.60 -h 100 -v 10 -d vs -c cvms -a d -s 0 -e 5000 -o cross_118.7x_34.5_cvms.png

#cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.5,-118.70 -u 34.5,-118.60 -h 100 -v 10 -d vs -c cvmsi -a d -s 0 -e 5000 -o cross_118.7x_34.5_cvmsi.png

#cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.5,-118.70 -u 34.5,-118.60 -h 100 -v 10 -d vs -c cvmh -a d -s 0 -e 5000 -o cross_118.7x_34.5_cvmh.png

#cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 35.21,-121 -u 35.21,-118.0 -h 100 -v 10 -d vs -c cca -a d -s 0 -e 5000 -o cross_121x_35.21_cca.png 

#cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 35.21,-121 -u 35.21,-118.0 -h 100 -v 10 -d vs -c cca -a b -s 0 -e 5000 -o cross_121x_35.21_cca_g.png -g 2.5

#cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 35.21,-119.39 -u 35.21,-119 -h 100 -v 10 -d vs -c cca -a d -s 0 -e 5000 -o cross_121x_35.21_cca.png 

#===========

#XXcd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.5,-118.70 -u 34.5,-118.60 -h 100 -v 10 -d vs -c cs173 -a d -s 0 -e 5000 -o cross_118.7x_34.5_cs173.png
cd ${UCVM_INSTALL_PATH}/utilities; ./plot_cross_section.py -b 34.5,-118.70 -u 34.5,-118.60 -h 100 -v 10 -d vs -c cca -a d -s 0 -e 5000 -o cross_118.7x_34.5_cca.png



