#!/bin/bash
#
#-b 33.349998,-123.000000 -u 39.355000,-115.245003 -c cca -s 0.005000 -x 1551 -y 1201
#
ARGS="-b 33.35,-123.000 -u 39.355,-115.245 -c cca -s 0.005000 -x 1551 -y 1201"
#ARGS="-b 32.000000,-125.750000 -u 43.000000,-114.449997 -c cca -s 0.005000 -x 2260 -y 2200"

#./plot_z25_map.py -f cca_z2.5.first -o cca_z2.5_first_map.png -e "(first crossing)" ${ARGS}
./plot_z25_map.py -f cca_z2.5.firstOrSecond -o cca_z2.5_firstOrSecond_map.png -e "(first or second crossing)" ${ARGS}
#./plot_z25_map.py -f cca_z2.5.last -o cca_z2.5_last_map.png -e "(last crossing)" ${ARGS}
#./plot_z25_map.py -f cca_z2.5.threeLast -o cca_z2.5_threeLast_map.png -e "(third or last crossing)" ${ARGS}
#./plot_z25_map.py -f cca_z2.5.secondOnly -o cca_z2.5_secondOnly_map.png -e "(second only crossing)" ${ARGS}

