#!/bin/sh  

#Request for etree
#From:   Esmaeilzadeh Seylabi, Elnaz <elnaz@caltech.edu>


etree_go () {
   sbatch ${SLURM_EXTRACT_SCRIPT}
}

etree_slurm() {

scriptfile=./${SLURM_EXTRACT_SCRIPT}

/bin/cat >$scriptfile << EEND 
#!/bin/bash
#SBATCH --ntasks=17
#SBATCH -N 4 
#SBATCH --mem 0 # Set to unlimited memory
#SBATCH --time=01:00:00 
#SBATCH -o ${PWD}/mpi_${LABEL}_${GTL}_extract_etree.out
#SBATCH -e ${PWD}/mpi_${LABEL}_${GTL}_extract_etree.err
#SBATCH --export=NONE 
#SBATCH --mail-user=mei@usc.edu
#SBATCH --mail-type=END

source /home/rcf-40/mei/setup_env_proj.sh

###############################################################################

cp ${UCVM_INSTALL}/bin/ucvm2etree_extract_MPI .
cp ${UCVM_INSTALL}/conf/ucvm.conf .

srun -v --mpi=pmi2 ./ucvm2etree_extract_MPI -f ${PWD}/${ETREE_CONFIG}
sbatch ${SLURM_SORT_SCRIPT}

EEND

scriptfile=./${SLURM_SORT_SCRIPT}

/bin/cat >$scriptfile << EEEND 
#!/bin/bash
#SBATCH --ntasks=16
#SBATCH -N 4 
#SBATCH --mem 0 # Set to unlimited memory
#SBATCH --time=02:00:00 
#SBATCH -o ${PWD}/mpi_${LABEL}_${GTL}_sort_etree.out
#SBATCH -e ${PWD}/mpi_${LABEL}_${GTL}_sort_etree.err
#SBATCH --export=NONE 
#SBATCH --mail-user=mei@usc.edu
#SBATCH --mail-type=END

source /home/rcf-40/mei/setup_env_proj.sh

###############################################################################

cp ${UCVM_INSTALL}/bin/ucvm2etree_sort_MPI .
cp ${UCVM_INSTALL}/conf/ucvm.conf .

srun -v --mpi=pmi2 ./ucvm2etree_sort_MPI -f ${PWD}/${ETREE_CONFIG}
sbatch ${SLURM_MERGE_SCRIPT}

EEEND

scriptfile=./${SLURM_MERGE_SCRIPT}

/bin/cat >$scriptfile << EEEEND 
#!/bin/bash
#SBATCH --ntasks=16
#SBATCH -N 4 
#SBATCH --mem 0 # Set to unlimited memory
#SBATCH --time=02:00:00 
#SBATCH -o ${PWD}/mpi_${LABEL}_${GTL}_merge_etree.out
#SBATCH -e ${PWD}/mpi_${LABEL}_${GTL}_merge_etree.err
#SBATCH --export=NONE 
#SBATCH --mail-user=mei@usc.edu
#SBATCH --mail-type=END


source /home/rcf-40/mei/setup_env_proj.sh

###############################################################################

cp ${UCVM_INSTALL}/bin/ucvm2etree_merge_MPI .
cp ${UCVM_INSTALL}/conf/ucvm.conf .

srun -v --mpi=pmi2 ./ucvm2etree_merge_MPI -f ${PWD}/${ETREE_CONFIG}

EEEEND
}

## generate the etree.conf
etree_foo() {

configfile=./${ETREE_CONFIG}

/bin/cat >$configfile << END 
#
# ${DATE}
#
# ${ETREE_CONFIG}
#

proj=geo-bilinear 
lon_0=-116.8593
lat_0=33.6403

lon_1=-116.6457
lat_1=33.7958

lon_2=-116.3984
lat_2=33.5572

lon_3=-116.6119
lat_3=33.4022

# Domain dimensions (meters):
x-size=35000.0000
y-size=26250.0000
z-size=4375.0000

# Max freq, points per wavelength, Vs min
max_freq=${MAX_FREQ}
ppwl=${PPWL}
vs_min=${VS_MIN}

# Blocks partition parameters:
nx=8
ny=6
 
# Max allowed size of octants in meters
max_octsize=10000.0

# Etree parameters and info
title=GarnerValley_${MAX_FREQ}hz_${PPWL}pts_${VS_MIN}ms
author=Mei_Hui_Su4Elnza
date=02/27/2019
outputfile=./${LABEL}_garnervalley_${MODEL}_${GTL}_${MAX_FREQ}hz_${PPWL}pts_${VS_MIN}ms.e
format=etree 

# UCVM parameters
#ucvmstr=${MODEL}
#ucvm_interp_zrange=0.0,350.0 
ucvmstr=${MODEL},svm:svm1d
ucvm_interp_zrange=Z1
ucvmconf=${UCVM_INSTALL}/conf/ucvm.conf

# Scratch
scratch=./scratch2

#
# Buffering parameters
#
# Etree buffer size in MB
buf_etree_cache=128
# Max octants to buffer for flat file during extraction
buf_extract_mem_max_oct=4194304
# Max octants to save in flat file before reporting full during extraction
buf_extract_ffile_max_oct=16000000
# Max octants to read from input flat file during sorting
buf_sort_ffile_max_oct=20000000
# Minimum number of octants between reports during merging
buf_merge_report_min_oct=10000000
# MPI send/recv octant buffer size during merging
buf_merge_sendrecv_buf_oct=4096
# Etree read/write octant buffer size during merging
buf_merge_io_buf_oct=4194304
END
}

##
#Elnaz,cvms5,SVM,5,10,200
#

UCVM_INSTALL="/home/scec-00/mei/ucvmc_19_4/install"

DATE=`date`

input="etree_input.txt"
while IFS= read -r file; do
  arrData=(${file//,/ })
  [[ $arrData =~ ^#.* ]] && continue
  LABEL=${arrData[0]}
  MODEL=${arrData[1]}
  GTL=${arrData[2]}
  MAX_FREQ=${arrData[3]}
  PPWL=${arrData[4]}
  VS_MIN=${arrData[5]}
  ETREE_CONFIG=mpi_${LABEL}_${MODEL}_${GTL}_${MAX_FREQ}hz_${PPWL}pts_${VS_MIN}ms.conf
  SLURM_EXTRACT_SCRIPT=mpi_${LABEL}_${GTL}_extract_etree.slurm
  SLURM_SORT_SCRIPT=mpi_${LABEL}_${GTL}_sort_etree.slurm
  SLURM_MERGE_SCRIPT=mpi_${LABEL}_${GTL}_merge_etree.slurm
  PWD=`pwd`

  etree_foo
  etree_slurm
  etree_go

done < "$input"

