#!/bin/bash
# for ORNL's titan => h2ologin.ncsa.illinois.edu

#/ccs/home/mei
#/lustre/atlas/proj-shared/geo112/mei

## setup environment on titan
module swap PrgEnv-pgi PrgEnv-gnu

## prepend velocity model's lib
export TEST_UCVMC_TARGET=/ccs/home/mei/scratch/TARGET_UCVMC
export UCVM_SRC_PATH=$TEST_UCVMC_TARGET/UCVMC
export UCVM_INSTALL_PATH=$TEST_UCVMC_TARGET/install

echo $UCVM_SRC_PATH

if [ $LD_LIBRARY_PATH ] ; then
  export LD_LIBRARY_PATH=$UCVM_INSTALL_PATH/lib/euclid3/lib:$UCVM_INSTALL_PATH/lib/proj-4/lib:$UCVM_INSTALL_PATH/model/cvms426/lib:$UCVM_INSTALL_PATH/model/cencal/lib:$UCVM_INSTALL_PATH/model/cca/lib:$LD_LIBRARY_PATH
  else
    export LD_LIBRARY_PATH=$UCVM_INSTALL_PATH/lib/euclid3/lib:$UCVM_INSTALL_PATH/lib/proj-4/lib:$UCVM_INSTALL_PATH/model/cvms426/lib:$UCVM_INSTALL_PATH/model/cencal/lib:$UCVM_INSTALL_PATH/model/cca/lib

fi
#echo $LD_LIBRARY_PATH

## setup python script
if [ $PYTHONPATH ] ; then 
  export PYTHONPATH=$PYTHONPATH:$UCVM_SRC_PATH/utilities/pycvm
  else
     export PYTHONPATH=$UCVM_SRC_PATH/utilities/pycvm
fi
#echo $PYTHONPATH

##rm -rf $TEST_UCVMC_TARGET 
##mkdir $TEST_UCVMC_TARGET

#cd $TEST_UCVMC_TARGET
#git clone https://github.com/meihuisu/UCVMC.git
#git clone https://github.com/SCECcode/UCVMC.git

cd $UCVM_SRC_PATH/largefiles; ./get_large_files.py

cd $UCVM_SRC_PATH/largefiles; ./check_largefiles_md5.py 
cd $UCVM_SRC_PATH/largefiles; ./stage_large_files.py

cd $UCVM_SRC_PATH
./ucvm_setup.py -s << EOF &> ucvm_setup_install.log
$UCVM_INSTALL_PATH
yes
yes
yes
yes
yes
yes
yes
EOF

cd $UCVM_SRC_PATH; make check

echo "..EXITING.."
exit


