#!/bin/bash

#PBS -l walltime=00:10:00
#PBS -l nodes=1
#PBS -e /ccs/home/mei/scratch/UCVM_REVIEW/RESULT/ornl_cca_query_proj.e
#PBS -o /ccs/home/mei/scratch/UCVM_REVIEW/RESULT/ornl_cca_query_proj.o
#PBS -q debug
#PBS -A GEO112

cd $PBS_O_WORKDIR
aprun -n 1 -j 1 /lustre/atlas/proj-shared/geo112/ucvm_18_5/install/bin/basin_query -f /lustre/atlas/proj-shared/geo112/ucvm_18_5/install/conf/ucvm.conf  -m cca -v 2500 < /lustre/atlas/proj-shared/geo112/ucvm_18_5/install/tests/test_latlonsonly.txt 


