#!/bin/bash

#PBS -l walltime=01:00:00
#PBS -l nodes=2
#PBS -e /ccs/home/mei/scratch/UCVM_REVIEW/RESULT/ornl_cca_z2.5_proj.e
#PBS -o /ccs/home/mei/scratch/UCVM_REVIEW/RESULT/ornl_cca_z2.5_proj.o
#PBS -A GEO112

export TEST_TOP_PATH=/ccs/home/mei/scratch/UCVM_REVIEW/RESULT
cd $PBS_O_WORKDIR

aprun -n 20 /lustre/atlas/proj-shared/geo112/ucvm_18_5/install/bin/basin_query_mpi -b ${TEST_TOP_PATH}/RESULT/ornl_cca_z2.5_proj.first,${TEST_TOP_PATH}/RESULT/ornl_cca_z2.5_proj.firstOrSecond,${TEST_TOP_PATH}/RESULT/ornl_cca_z2.5_proj.last,${TEST_TOP_PATH}/RESULT/ornl_cca_z2.5_proj.secondOnly,${TEST_TOP_PATH}/RESULT/ornl_cca_z2.5_proj.threeLast -o ${TEST_TOP_PATH}/RESULT/ornl_cca_z2.5_proj.result -f /lustre/atlas/proj-shared/geo112/ucvm_18_5/install/conf/ucvm.conf -m cca -i 20 -v 2500 -l 33.35,-123.0 -s 0.005 -x 1551 -y 1201

echo "Jobs done"
exit 0



