#!/bin/bash
#PBS -l walltime=08:00:00,nodes=10:ppn=2:xe
#PBS -A baln
#PBS -e /u/sciteam/meisu/scratch/UCVM_REVIEW/RESULT/basin_query_mpi_cvms5_z1.0_n20.err
#PBS -o /u/sciteam/meisu/scratch/UCVM_REVIEW/RESULT/basin_query_mpi_cvms5_z1.0_n20.out

## prepend velocity model's lib
export TEST_UCVMC_TARGET=/projects/sciteam/baln/meisu/TARGET_UCVMC
export UCVM_SRC_PATH=$TEST_UCVMC_TARGET/UCVMC
export UCVM_INSTALL_PATH=$TEST_UCVMC_TARGET/install

if [ $LD_LIBRARY_PATH ] ; then
  export LD_LIBRARY_PATH=$UCVM_INSTALL_PATH/lib/euclid3/lib:$UCVM_INSTALL_PATH/lib/proj-4/lib:$UCVM_INSTALL_PATH/model/cvms426/lib:$UCVM_INSTALL_PATH/model/cencal/lib:$LD_LIBRARY_PATH
  else
    export LD_LIBRARY_PATH=$UCVM_INSTALL_PATH/lib/euclid3/lib:$UCVM_INSTALL_PATH/lib/proj-4/lib:$UCVM_INSTALL_PATH/model/cvms426/lib:$UCVM_INSTALL_PATH/model/cencal/lib
fi
#echo $LD_LIBRARY_PATH

export TEST_TOP_PATH=/u/sciteam/meisu/scratch/UCVM_REVIEW
export TEST_SRC_PATH=${TEST_TOP_PATH}/UCVMC_TEST/ncsa/basinQuery

###############################################################################

cd $PBS_O_WORKDIR
cp ${UCVM_INSTALL_PATH}/bin/basin_query_mpi .
cp ${UCVM_INSTALL_PATH}/conf/ucvm.conf .


#CVM-S4.26 and CVM-S4.26-M01: [minLat = 31.0, minLon = -121.0, nx = 1701, ny = 1101, gridSpacing = 0.005 degrees]

aprun -n 20 ./basin_query_mpi -b ${TEST_TOP_PATH}/RESULT/basin_query_mpi_cvms5_z1.0_n20_first.result,${TEST_TOP_PATH}/RESULT/basin_query_mpi_cvms5_z1.0_n20_second.result -o ${TEST_TOP_PATH}/RESULT/basin_query_mpi_cvms5_z1.0_n20.result -f ucvm.conf -m cvms5 -i 20 -v 1000 -l 31.0,-121.0 -s 0.005 -x 1701 -y 1101

echo "Jobs done"
exit 0

